In [1]:
import llm4series as ls

In [2]:
ts = ls.read_file("data/OT.csv")

In [3]:
prediction = ts * 1.1

In [4]:
ts.metrics(prediction)

         OT
smape  9.52
mae    2.66
rmse   2.91

In [5]:
print(ts.smape(prediction), ts.mae(prediction), ts.rmse(prediction))

9.52 2.66 2.91

In [6]:
ts.smape(prediction, decimals=1)

np.float64(9.5)

In [7]:
ts = ls.read_file("data/ETTh2.csv")

In [8]:
prediction = ts * 1.1

In [9]:
ts.metrics(prediction)

       HUFL  HULL  MUFL  MULL  LUFL  LULL    OT
smape  9.49  7.43  9.52  8.94  8.87  6.36  9.52
mae    3.72  0.87  4.38  0.84  0.60  0.26  2.66
rmse   3.86  1.04  4.57  0.94  0.70  0.64  2.91

In [10]:
print(ts.smape(prediction), ts.mae(prediction), ts.rmse(prediction))

HUFL    9.49
HULL    7.43
MUFL    9.52
MULL    8.94
LUFL    8.87
LULL    6.36
OT      9.52
dtype: float64 HUFL    3.72
HULL    0.87
MUFL    4.38
MULL    0.84
LUFL    0.60
LULL    0.26
OT      2.66
dtype: float64 HUFL    3.86
HULL    1.04
MUFL    4.57
MULL    0.94
LUFL    0.70
LULL    0.64
OT      2.91
dtype: float64

In [11]:
ts.smape(prediction, decimals=1)

HUFL    9.5
HULL    7.4
MUFL    9.5
MULL    8.9
LUFL    8.9
LULL    6.4
OT      9.5
dtype: float64

In [12]:
import pandas as pd

df1 = pd.DataFrame(ts * 1.1)
df2 = pd.DataFrame(ts * 1.2)
display(ls.metrics(df1, df2))

list1 = list(ts["OT"] * 1.1)
list2 = list(ts["OT"] * 1.2)
display(ls.metrics(list1, list2))

      smape   mae  rmse
HUFL   8.67  3.72  3.86
HULL   6.78  0.87  1.04
MUFL   8.70  4.38  4.57
MULL   8.16  0.84  0.94
LUFL   8.10  0.60  0.70
LULL   5.80  0.26  0.64
OT     8.70  2.66  2.91

       value
smape   8.70
mae     2.66
rmse    2.91